#!/bin/sh
bootmedium=spi_nand
CMDLINE_FILE=${CMDLINE_FILE:-/proc/cmdline}
BY_NAME_DIR=${BY_NAME_DIR:-/dev/block/by-name}

select_slot(){
slot_suffix=
slot_seen=0
cmdline=$(cat "$CMDLINE_FILE") || return 1
for bootarg in $cmdline; do
case "$bootarg" in
	androidboot.slot_suffix=_a)
		new_slot_suffix=_a
		;;
	androidboot.slot_suffix=_b)
		new_slot_suffix=_b
		;;
	androidboot.slot_suffix=*)
		printf 'Invalid androidboot.slot_suffix: %s\n' "$bootarg" >&2
		return 1
		;;
	*)
		continue
		;;
esac
if [ "$slot_seen" -eq 1 ] && [ "$slot_suffix" != "$new_slot_suffix" ]; then
	printf 'Conflicting androidboot.slot_suffix values\n' >&2
	return 1
fi
slot_suffix=$new_slot_suffix
slot_seen=1
done
if [ "$slot_seen" -eq 0 ]; then
	slot_suffix=_a
fi
}

make_link(){
link_target=$1
link_name=$2
if [ -L "$link_name" ]; then
	rm -f "$link_name" || return 1
elif [ -e "$link_name" ]; then
	printf 'Refusing to replace non-symlink: %s/%s\n' "$BY_NAME_DIR" "$link_name" >&2
	return 1
fi
ln -s "$link_target" "$link_name" || return 1
}

linkdev(){
select_slot || return 1
mkdir -p "$BY_NAME_DIR" || return 1
cd "$BY_NAME_DIR" || return 1
make_link /dev/mtd0 env || return 1
make_link /dev/mtd1 idblock || return 1
make_link /dev/mtd2 uboot || return 1
make_link /dev/mtd3 boot_a || return 1
make_link /dev/mtd4 boot_b || return 1
make_link /dev/mtd5 rootfs_a || return 1
make_link /dev/mtd6 rootfs_b || return 1
make_link /dev/mtd7 oem_a || return 1
make_link /dev/mtd8 oem_b || return 1
make_link /dev/mtd9 reserved || return 1
make_link /dev/mtd10 misc || return 1
make_link /dev/mtd11 userdata || return 1
make_link "boot${slot_suffix}" boot || return 1
make_link "rootfs${slot_suffix}" rootfs || return 1
make_link "oem${slot_suffix}" oem || return 1
}
mount_part(){
if [ -z "$1" -o -z "$2" -o -z "$3" ];then
	echo "Invalid paramter, exit !!!"
	exit 1
fi
root_dev=$(mountpoint -n /)
root_dev=${root_dev%% *}
partname=$1
part_dev=/dev/block/by-name/$1
mountpt=$2
part_fstype=$3
part_realdev=$(realpath $part_dev)
if [ ! -d $mountpt ]; then
	if [ "$mountpt" = "IGNORE" -a "emmc" = "$bootmedium" ];then
		if [ "$root_dev" = "$part_realdev" ];then
			resize2fs $part_dev
		fi
		return 0;
	else
		echo "${0} info: mount point path [$mountpt] not found, skip..."
		return 1;
	fi
fi
if test -h $part_dev; then
case $bootmedium in
	emmc)
		if [ "$root_dev" = "$part_realdev" ];then
			resize2fs $part_dev
		else
			e2fsck -y $part_dev
			mount -t $part_fstype $part_dev $mountpt
			if [ $? -eq 0 ]; then
				resize2fs $part_dev
				tune2fs $part_dev -L $partname
			else
				echo "mount $partname error, try to format..."
				mke2fs -F -L $partname $part_dev  && 					tune2fs -c 0 -i 0 $part_dev && 					mount -t $part_fstype $part_dev $mountpt
			fi
		fi
		;;
	spi_nand|slc_nand)
		if [ $partname = "rootfs" ];then
			echo "rootfs mount on $root_dev"
		elif [ "$part_fstype" = "ubifs" ]; then
			part_no=$(echo $part_realdev | grep -oE "[0-9]*$")
			ubi_dev=/dev/ubi${part_no}
			ubi_vol=${ubi_dev}_0
			mount | grep $ubi_vol
			if [ $? -eq 0 ];then
				echo "***********$partname has been mounted***********"
			else
				if [ ! -e $ubi_vol ];then
					echo "***********$ubi_vol not exist***********"
					if [ ! -e $ubi_dev ];then
						echo "***********$ubi_dev not exist***********"
						ubiattach /dev/ubi_ctrl -m $part_no -d $part_no
						if [ $? -ne 0 ];then
							echo "ubiattach $part_realdev error, try to format..."
							ubiformat -y $part_realdev
							ubiattach /dev/ubi_ctrl -m $part_no -d $part_no
						fi
					fi
					ubi_info_dir=/sys/class/ubi/ubi${part_no}
					avail_eraseblocks=$(cat $ubi_info_dir/avail_eraseblocks)
					eraseblock_size=$(cat $ubi_info_dir/eraseblock_size)
					echo "try to make volume: $ubi_vol ..."
					ubimkvol $ubi_dev -N $partname -s $((avail_eraseblocks*eraseblock_size))
				fi
				mount -t $part_fstype $ubi_vol $mountpt
			fi
		elif [ "$part_fstype" = "squashfs" ]; then
			part_no=$(echo $part_realdev | grep -oE "[0-9]*$")
			ubi_dev=/dev/ubi${part_no}
			ubi_vol=${ubi_dev}_0
			ubi_block=/dev/ubiblock${part_no}_0
			mount | grep $ubi_block
			if [ $? -eq 0 ];then
				echo "***********$partname has been mounted***********"
			else
				if [ ! -e $ubi_block ];then
					echo "***********$ubi_block not exist***********"
					ubiattach /dev/ubi_ctrl -m $part_no -d $part_no
					if [ $? -ne 0 ];then
						echo "ubiattach $part_realdev error, return !!!"
						echo "Please check the device: $part_realdev"
						return 1
					fi
					ubiblock -c $ubi_vol
				fi
				mount -t $part_fstype $ubi_block $mountpt
			fi
		elif [ "$part_fstype" = "erofs" ]; then
			part_no=$(echo $part_realdev | grep -oE "[0-9]*$")
			ubi_dev=/dev/ubi${part_no}
			ubi_vol=${ubi_dev}_0
			ubi_block=/dev/ubiblock${part_no}_0
			mount | grep $ubi_block
			if [ $? -eq 0 ];then
				echo "***********$partname has been mounted***********"
			else
				if [ ! -e $ubi_block ];then
					echo "***********$ubi_block not exist***********"
					ubiattach /dev/ubi_ctrl -m $part_no -d $part_no
					if [ $? -ne 0 ];then
						echo "ubiattach $part_realdev error, return !!!"
						echo "Please check the device: $part_realdev"
						return 1
					fi
					ubiblock -c $ubi_vol
				fi
				mount -t $part_fstype $ubi_block $mountpt
			fi
		else
			echo "Error: wrong filesystem type: $part_fstype, return !!!"
			return 1
		fi
		;;
	spi_nor)
		if [ "$root_dev" = "$part_realdev" ];then
			echo "***********$part_dev has been mounted, skipping***********"
		else
			echo "mount -t $part_fstype $part_dev $mountpt"
			mount -t $part_fstype $part_dev $mountpt
			if [ $? -eq 0 ]; then
				echo "***********succeed in mounting***********"
			elif [ "$part_fstype" = "jffs2" ]; then
				echo "mount $partname error, try to format..."
				echo "flash_erase -j ${part_realdev/block/} 0 0 && mount -t $part_fstype $part_dev $mountpt"
				flash_erase -j ${part_realdev/block/} 0 0 && mount -t $part_fstype $part_dev $mountpt
			else
				echo "mount $partname error, skipping! Please check the filesystem."
			fi
		fi
		;;
	*)
		echo "Invalid Parameter: Check bootmedium !!!"
		exit 1
		;;
esac
fi
}
case "$1" in
start)
	linkdev || exit 1
	mount_part rootfs IGNORE squashfs || exit 1
	mount_part oem /oem squashfs || exit 1
	mount_part userdata /userdata ubifs || exit 1
	;;
linkdev)
	linkdev || exit 1
	;;
stop)
	printf '%s\n' "stop $0 finished"
	;;
*)
	printf 'Usage: %s {start|linkdev|stop}\n' "$0" >&2
	exit 1
	;;
esac
